version: '3'
services:
  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - "27017:27017"
    networks:
    - my_network_name

  web: 
    build: .
    ports:
      - '9000:8081'
    depends_on:
      - mongodb
    networks:
      - my_network_name

networks:
    my_network_name:
        driver: bridge